docs_dir: docs/
site_name: Soteria User Manuals
site_url: https://ua-data7.github.io/user-manuals
site_description: Soteria User Documentation
site_author: 'Soteria CyVerse Health'

# uncomment to show the github icon in the header with
# number of forks & stars
repo_url: https://github.com/ua-data7/user-manuals
edit_uri: edit/mkdocs-material/docs

# Copyright
copyright: 'Copyright &copy; 2023 University of Arizona Data Science Institute, Arizona Board of Regents'


# Navigation Pane

nav:
  - About Soteria: 'index.md'
  - Logging in & Access:
    - Virtual Private Network (VPN): 'vpn.md'
    - High Performance Computing Center: 'hpc.md'
    - Globus Data Transfer: 'Soteria/Globus.md'
    - Soteria Access (Mac): 'Soteria/SoteriaAccess-Mac.md'
    - Soteria Access (Windows): 'Soteria/SoteriaAccess-Windows.md'
    - UA HPC Soteria: 'Soteria/UAHPC_Soteria.md'

# JavaScript for Intercom Widget
extra_javascript:
  - javascripts/intercom.js

# logos
imgwidth: 70px;
theme:
  highlightjs: true
  name: material
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo: 'images/uarizona.png'
  favicon: 'images/favicon.ico'
# setting features for the navigation tab
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
  # Default values, taken from mkdocs_theme.yml
  language: en
  # custom_dir: 'overrides'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: white)"
      primary: 'white'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

# Customization
extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/
    - icon: fontawesome/brands/github
      link: https://github.com/cyverse/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cyverseorg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cyverse.org
    - icon: fontawesome/brands/docker
      link: https://harbor.cyverse.org/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/CyverseOrgProject
  analytics:
    provider: google
    property: G-6WMK2Y07YW

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
